# SPDX-License-Identifier: Apache-2.0

"""Turning what you wrote into a plugin that patches the client.

The APK is never rewritten. Dalvik bytecode cannot be assembled back into a
running app without repacking and re-signing it, and repacking it means a
client that has to be reinstalled, loses its data directory and stops
updating. So a patch is a *plugin*: it loads with the client and hooks the
methods you named, and turning it off puts the client back exactly as it was.

That is not a lesser version of patching the APK. It is reversible, it
survives a client update as long as the method is still there, and it is the
one form of patching that a user can undo from the plugin list at four in the
morning when it turns out to break something.

Two things are generated here — a hook skeleton aimed at one method, and the
plugin that carries whatever skeletons you filled in — and both are plain
text, so all of it is testable without a phone.
"""

import os
import re

from . import dex as dex_module

# What a hook file may define. `apply` is called once with the plugin; that is
# the whole contract, deliberately, because anything richer would be a
# framework somebody has to learn before they can change one method.
ENTRY = "apply"

# Where the generated plugin puts things. Same shape as any other plugin, so
# `plugin install` and everything else already knows what to do with it.
MAIN = "src/BasePlugin.py"
PACKAGE = "src"
HOOK_PACKAGE = "src/hooks"

REFMAP = """metainfo: meta.yml
main: %s
""" % MAIN


def hook_files(root):
    """The hook modules in a workspace, by their module name."""
    directory = os.path.join(str(root), "hooks")
    try:
        found = sorted(name for name in os.listdir(directory)
                       if name.endswith(".py") and not name.startswith("_"))
    except Exception:
        return []
    return [(name[:-3], os.path.join(directory, name)) for name in found]


def module_name(text):
    """A file name that is also a legal Python module name."""
    cleaned = re.sub(r"[^0-9A-Za-z_]", "_", str(text or "").strip())
    cleaned = cleaned.strip("_") or "hook"
    if cleaned[0].isdigit():
        cleaned = "hook_" + cleaned
    return cleaned.lower()[:48]


# ------------------------------------------------------------- the skeleton


def skeleton(class_name, method=None, dex_name=None):
    """A hook aimed at one method, ready to be filled in.

    Written against the parts of the SDK that are certain — `MethodHook` with
    `before_hooked_method` and `after_hooked_method`, and Java reflection for
    finding the method — with the one uncertain call, how this build of the
    SDK wants `hook_method` to be spelled, behind a helper that tries the
    forms rather than betting on one. A generated file that does not run is
    worse than no generator.
    """
    signature = method.descriptor_signature() if method is not None else None
    name = method.name if method is not None else "theMethod"
    parameters = list(method.parameters) if method is not None else []
    return "\n".join([
        "# A patch for %s" % class_name,
        "#",
        "# Generated by `patch hook`. Everything below runs inside the",
        "# client, so what you can reach here is what the client can reach.",
        "%s" % ("# Found in %s." % dex_name if dex_name else "#"),
        "",
        "from base_plugin import MethodHook",
        "",
        "from ._api import attach, find_method",
        "",
        'CLASS = "%s"' % class_name,
        'METHOD = "%s"' % name,
        "",
        "# The parameter types, so the right overload is found. Taken from the",
        "# dex, which is why they are descriptors rather than names.",
        "TYPES = %s" % _types_literal(parameters),
        "",
        ("# %s" % signature) if signature else "",
        "",
        "",
        "class Patch(MethodHook):",
        '    """What happens around the method."""',
        "",
        "    def before_hooked_method(self, param):",
        '        """Runs before the original. `param.args` are its arguments;',
        "        setting `param.result` here skips the original entirely.",
        '        """',
        "        pass",
        "",
        "    def after_hooked_method(self, param):",
        '        """Runs after the original. `param.result` is what it',
        "        returned, and assigning to it changes what the caller sees.",
        '        """',
        "        pass",
        "",
        "",
        "def %s(plugin):" % ENTRY,
        '    """Called once, when the patch loads."""',
        "    method = find_method(CLASS, METHOD, TYPES)",
        "    attach(plugin, method, Patch())",
        "",
    ])


def _types_literal(parameters):
    if not parameters:
        return "()"
    inner = ", ".join('"%s"' % one for one in parameters)
    return "(%s,)" % inner if len(parameters) == 1 else "(%s)" % inner


def example():
    """The file a fresh workspace starts with.

    A worked example rather than an empty directory: the shape of a hook is
    three things nobody guesses on the first try — where the class comes from,
    what `param` holds, and that `apply` is what gets called.
    """
    return "\n".join([
        "# An example. Delete it, or change it into something.",
        "#",
        "# This one does nothing but say, in the client's log, every time",
        "# a chat is opened — which is enough to prove a patch is loaded",
        "# and running before you write one that matters.",
        "",
        "from android_utils import log",
        "from base_plugin import MethodHook",
        "",
        "from ._api import attach, find_method",
        "",
        'CLASS = "org.telegram.ui.ChatActivity"',
        'METHOD = "onResume"',
        "",
        "",
        "class Watch(MethodHook):",
        "    def after_hooked_method(self, param):",
        '        log("patch: a chat was opened")',
        "",
        "",
        "def %s(plugin):" % ENTRY,
        "    method = find_method(CLASS, METHOD, ())",
        "    attach(plugin, method, Watch())",
        "",
    ])


def api():
    """The helper every generated hook imports.

    It exists because two things about the SDK cannot be known from here with
    certainty: exactly how `hook_method` wants to be called, and how a class
    is best looked up in this build. Both are *probed* — every form tried in
    turn, the working one used — which is the same thing this plugin already
    does for installing a plugin and for the client's checkbox.

    Guessing one form and generating it into every hook file would mean, if
    the guess were wrong, a workspace full of files that all fail the same way
    and no obvious reason why.
    """
    return '''# Generated by extCLI. Shared by the hooks next to it.
"""Finding a method in the client, and hooking it.

Both are probed rather than assumed. This file is generated with no way to
know exactly how the installed SDK spells these calls, so it tries the forms
that exist and uses whichever answers.
"""

from android_utils import log


def find_class(name):
    """The client's class of that name, however this build finds one."""
    problems = []
    try:
        from hook_utils import find_class as sdk_find_class

        return sdk_find_class(name)
    except Exception as e:
        problems.append("hook_utils: %s" % e)
    try:
        from java import jclass

        return jclass(name)
    except Exception as e:
        problems.append("jclass: %s" % e)
    raise RuntimeError("cannot find %s (%s)" % (name, "; ".join(problems)))


def find_method(class_name, method_name, types=()):
    """One method of one class, picked by its parameter types.

    `types` are dex descriptors — `Ljava/lang/String;`, `I`, `[B` — because
    that is what `patch hook` reads them from. With none given and several
    overloads present, the first is taken and the choice is logged, which is
    better than failing on a method somebody almost certainly meant.
    """
    holder = find_class(class_name)
    wanted = [_descriptor(one) for one in types]
    found = []
    for method in holder.getDeclaredMethods():
        if str(method.getName()) != method_name:
            continue
        actual = [str(one.getName()) for one in method.getParameterTypes()]
        if not types:
            found.append(method)
        elif actual == wanted:
            return _open(method)
        else:
            found.append(method)
    if not found:
        raise RuntimeError("%s has no method %s" % (class_name, method_name))
    if types:
        log("patch: no %s.%s%s; using %s" % (class_name, method_name,
                                             tuple(wanted), found[0]))
    elif len(found) > 1:
        log("patch: %s.%s has %d overloads; using the first"
            % (class_name, method_name, len(found)))
    return _open(found[0])


def _open(method):
    try:
        method.setAccessible(True)
    except Exception:
        pass
    return method


_PRIMITIVES = {"V": "void", "Z": "boolean", "B": "byte", "S": "short",
               "C": "char", "I": "int", "J": "long", "F": "float",
               "D": "double"}


def _descriptor(text):
    """A dex descriptor as the name Java reflection reports.

    `Ljava/lang/String;` is `java.lang.String`, `[I` is `[I` — arrays keep
    their descriptor in reflection, which is the one place the two notations
    happen to agree.
    """
    text = str(text)
    if text.startswith("["):
        return text
    if text.startswith("L") and text.endswith(";"):
        return text[1:-1].replace("/", ".")
    return _PRIMITIVES.get(text, text)


def attach(plugin, method, hook, priority=50):
    """Registers `hook` for `method`. Returns what the SDK handed back.

    The call is tried in the forms this SDK might want rather than in the one
    it probably wants: a wrong guess here would break every hook in the patch
    identically and say nothing about why.
    """
    attempts = (
        ("hook_method(method, hook)",
         lambda: plugin.hook_method(method, hook)),
        ("hook_method(method, hook, priority)",
         lambda: plugin.hook_method(method, hook, priority)),
        ("hook_method(method=..., callback=...)",
         lambda: plugin.hook_method(method=method, callback=hook)),
    )
    problems = []
    for description, attempt in attempts:
        try:
            handle = attempt()
        except TypeError as e:
            problems.append("%s: %s" % (description, e))
            continue
        log("patch: hooked %s" % method)
        return handle
    raise RuntimeError("cannot hook %s (%s)" % (method, "; ".join(problems)))
'''


# ------------------------------------------------------------- the plugin


def loader(modules):
    """The generated plugin's entry point.

    Every hook is imported by name and applied one at a time, each in its own
    try: one hook aimed at a method a client update has moved must not stop
    the other four from loading. What failed is logged with the name of the
    file it came from, which is the only thing that makes a broken patch
    fixable.
    """
    names = list(modules)
    lines = [
        "# pyright: reportMissingImports=false",
        "# Generated by extCLI `patch build`. Edit the hooks, not this file.",
        "",
        "from android_utils import log",
        "from base_plugin import BasePlugin",
        "",
    ]
    for number, name in enumerate(names):
        lines.append("from .hooks import %s as _hook_%d" % (name, number))
    lines.extend([
        "",
        "HOOKS = (",
    ])
    for number, name in enumerate(names):
        lines.append('    ("%s", _hook_%d),' % (name, number))
    lines.extend([
        ")",
        "",
        "",
        "class Main(BasePlugin):",
        "    def on_plugin_load(self):",
        "        done = 0",
        "        for name, module in HOOKS:",
        "            try:",
        "                module.%s(self)" % ENTRY,
        "                done += 1",
        "            except Exception as e:",
        "                # one hook aimed at a method a client update has",
        "                # moved must not take the others down with it",
        '                log("patch: %s failed: %s: %s"',
        "                    % (name, type(e).__name__, e))",
        '        log("patch: %d of %d hooks applied" % (done, len(HOOKS)))',
        "",
        "    def on_plugin_unload(self):",
        '        log("patch: unloaded")',
        "",
    ])
    return "\n".join(lines)


def description(modules, changes=None):
    """The line the client shows under the patch's name."""
    del changes
    names = list(modules)
    if not names:
        return "A patch built by extCLI. It hooks nothing."
    return "Hooks the client: %s" % ", ".join(names)


def report(name, modules, source, when=None):
    """The file that goes inside the archive."""
    import time

    stamp = time.strftime("%Y-%m-%d %H:%M", time.localtime(when or time.time()))
    out = ["# %s" % name, "",
           "Built by extCLI on %s from %s." % (stamp, source), "",
           "This is a patch of the client. It does not change the APK: it",
           "hooks the methods below as it loads, and turning it off in the",
           "plugin list puts the client back exactly as it was.", ""]
    if not modules:
        out.append("It hooks nothing — there were no hooks to build.")
        return out
    out.append("## Hooks")
    out.append("")
    for one in modules:
        out.append("* `%s`" % one)
    return out


def build(work, target, mark, source="the client", when=None, author=""):
    """Writes the workspace's hooks out as an installable plugin.

    Only `hooks/` goes in. The index and the listings in the workspace are
    what you read while deciding what to write; putting them in the archive
    would ship two megabytes of class names to do nothing.

    Entries are sorted and the archive is deflated, so building the same hooks
    twice gives the same bytes.
    """
    import zipfile

    from . import workspace as workspace_module

    found = hook_files(work)
    if not found:
        return False, "there are no hooks in %s/ to build" % "hooks"
    names = [name for name, _path in found]
    plugin_name = workspace_module.plugin_name(mark)

    meta = {
        "name": plugin_name,
        "id": workspace_module.plugin_id(mark),
        "version": "0+patch.%s" % mark,
        "description": description(names),
        "author": author or "extCLI",
        "app_version": ">=12.9.0",
        "sdk_version": ">=1.4.5.1",
    }

    try:
        with zipfile.ZipFile(str(target), "w", zipfile.ZIP_DEFLATED) as out:
            out.writestr("refmap.yml", REFMAP)
            out.writestr("meta.yml", _meta_text(meta))
            out.writestr("%s/__init__.py" % PACKAGE, "")
            out.writestr(MAIN, loader(names))
            out.writestr("%s/__init__.py" % HOOK_PACKAGE, "")
            out.writestr("%s/_api.py" % HOOK_PACKAGE, _api_text(work))
            for name, path in found:
                with open(path, "r", encoding="utf-8") as handle:
                    out.writestr("%s/%s.py" % (HOOK_PACKAGE, name),
                                 handle.read())
            out.writestr("PATCH.md", "\n".join(
                report(plugin_name, names, source, when=when)) + "\n")
    except Exception as e:
        try:
            os.remove(str(target))
        except Exception:
            pass
        return False, "%s: %s" % (type(e).__name__, e)
    return True, plugin_name


def _api_text(work):
    """The helper, as the workspace has it — edits to it are somebody's own."""
    path = os.path.join(str(work), "hooks", "_api.py")
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read()
    except Exception:
        return api()


def _meta_text(fields):
    from . import pack

    return pack.render(fields, order=("name", "id", "version", "description",
                                      "author"))


def method_of(dex, class_name, method_name):
    """The dex's own record of a method, for a skeleton to be built from."""
    _fields, methods = dex.members(class_name)
    wanted = [one for one in methods if one.name == method_name]
    if not wanted:
        known = sorted({one.name for one in methods})
        raise dex_module.DexError(
            "%s has no method %s" % (class_name, method_name)
            + (" (it has %s)" % ", ".join(known[:8]) if known else ""))
    # the one with the most parameters is the one somebody usually means: the
    # short overloads are almost always convenience wrappers around it
    return sorted(wanted, key=lambda one: len(one.parameters))[-1]
